language: node_js

node_js:
  - stable

install:
  - npm install
  - npm run build

script:
  - npm run cover

cache:
  directories:
    - 'node_modules'
# Send coverage data to Coveralls
after_script: 'cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js'
